"""Changed the price from Integer to Float

Revision ID: 00682e54b85c
Revises: cb9c95c3cb0d
Create Date: 2024-04-26 14:28:20.030561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00682e54b85c'
down_revision = 'cb9c95c3cb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
